module.exports = {
    MEMBER_REPORT: 'MEMBER_REPORT',
    RESET_FORM: 'RESET_FORM',

    SHOW_ALARM_EDIT_MODAL: 'SHOW_ALARM_EDIT_MODAL',
    CLOSE_ALARM_EDIT_MODAL: 'CLOSE_ALARM_EDIT_MODAL',

    SHOW_ACTIVE_ALARM_MODAL: 'SHOW_ACTIVE_ALARM_MODAL',
    CLOSE_ACTIVE_ALARM_MODAL: 'CLOSE_ACTIVE_ALARM_MODAL',

    TEST_REDUCER: 'TEST_REDUCER',

    ADD_ALARM: 'ADD_ALARM',
    EDIT_ALARM: 'EDIT_ALARM',
    DELETE_ALARM: 'DELETE_ALARM',

    SET_CURRENT_ALARM_INDEX: "SET_CURRENT_ALARM_INDEX",
    SET_CURRENT_ALARM: 'SET_CURRENT_ALARM',


};

